### ISSUE TITLE
Error in if (is.na(idx1))

### ISSUE THREAD

**Issue by marcomick** [openvolley/datavolley#1]
Hello! When i try to test the parser with my dvw files i get the error (running the line "x <- read_dv(system.file("extdata/myfile.dvw",package="datavolley"),insert_technical_timeouts=FALSE)"):

Error in if (is.na(idx1)) idx1 <- 15 : argument is of length zero
In addition: Warning message:
In file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former

which could be the reason?

thank you.

Marco

**Comment by raymondben** [comment]
Hi Marco
The `system.file` function looks for files that were bundled as part of a package. To read your own files you just want something like:
`x <- read_dv("c:/somewhere/myfile.dvw",insert_technical_timeouts=FALSE)`

The cryptic error message you are getting is just because it can't find the file. I will fix it so that the error message is more informative. Thanks for reporting it!

**Comment by marcomick** [comment]
Uhm.. but i put myfile in the same directory of the example files. Anyway
i'll try to specify the path and i'll let you know if it works! Thank you
for your answer!!!

Marco

Il giorno sab 22 lug 2017 alle 00:15 Ben Raymond <notifications@github.com>
ha scritto:

**Comment by raymondben** [comment]
Oh. OK, I'll look further!

**Comment by marcomick** [comment]
Thanks!



Il giorno sab 22 lug 2017 alle 00:19 Ben Raymond <notifications@github.com>
ha scritto:

**Comment by raymondben** [comment]
Hi again Marco
I'm pretty sure it's not finding that file. If you do:
`system.file("extdata/myfile.dvw",package="datavolley")`
I think it will return `""` (empty string - meaning that it can't find that file).
It *should* be finding the file if you have copied it into the library location (which will be given by  `system.file("extdata",package="datavolley")`) but overall I think you are better to keep your files separate from the library. Otherwise, if you upgrade/reinstall the datavolley package, you will lose those files because it will overwrite that folder.
So try putting your file in some other folder and referencing it directly:
`x <- read_dv("c:/somewhere/myfile.dvw",insert_technical_timeouts=FALSE)`
Let me know how that goes!
(PS I've added some more checking of inputs and updated the error messages, so you might like to reinstall the datavolley package).

**Comment by marcomick** [comment]
ok! i've modified the code as you suggested and it's working! thank you
Ben!!



2017-07-22 11:06 GMT+02:00 Ben Raymond <notifications@github.com>:

**Comment by raymondben** [comment]
Great! I'll close this issue but feel free to open another or contact me directly if you have others.
