### ISSUE TITLE
court_colour

### ISSUE THREAD

**Issue by tyler-widdison** [openvolley/datavolley#3]
When doing `xend yend` the court color is covering up the lines. Inside the court boundaries. Outside the court boundaries you can see the lines. 

![image](https://user-images.githubusercontent.com/51216700/104769126-06d91680-572c-11eb-8149-32b37e2d8ced.png)

**Comment by raymondben** [comment]
Hrmph, good catch. That issue must have been there for a long time, it happens with `court_colour = "indoor"` (or any non-NULL court colour) as well. The immediate solution is to draw the court first before the actual data, i.e.:
```
ggplot(xserves, aes(start_coordinate_x, start_coordinate_y,
                                xend = end_coordinate_x, yend = end_coordinate_y, colour = evaluation)) +
     ggcourt(labels = c("Serving team", "Receiving team"), court_colour = "beach") +
     geom_segment(arrow = arrow(length = unit(2, "mm"), type = "closed", angle = 20)) +
     scale_colour_manual(values = c(Ace = "limegreen", Error = "firebrick", Other = "dodgerblue"),
                         name = "Evaluation")
```
instead of putting the court last.
Longer term we might need to refactor `ggcourt` to give greater control over what gets plotted. Conceivably one might want e.g. the court colour and lines plotted, then data, then zone labels or court labels over the top of those.

**Comment by raymondben** [comment]
Huh, seems that past me already thought of this:

**Comment by tyler-widdison** [comment]
👍

**Comment by raymondben** [comment]
Huh, seems that past me already thought of this:
```
ggplot(xserves, aes(start_coordinate_x, start_coordinate_y,
                    xend = end_coordinate_x, yend = end_coordinate_y, colour = evaluation)) +
  ggcourt(court_colour = "beach", background_only = TRUE) +
  geom_segment(arrow = arrow(length = unit(2, "mm"), type = "closed", angle = 20)) +
  ggcourt(labels = c("Serving team", "Receiving team"), foreground_only = TRUE) +
  scale_colour_manual(values = c(Ace = "limegreen", Error = "firebrick", Other = "dodgerblue"),
                      name = "Evaluation")
```

![beach_layered](https://user-images.githubusercontent.com/6445827/104787478-bb823f00-57e3-11eb-8904-697825559e88.png)
