### ISSUE TITLE
Dig extended skills

### ISSUE THREAD

**Issue by tyler-widdison** [openvolley/datavolley#4]
After parsing some dvws with datavolley, the special_code translation of this:
![image](https://user-images.githubusercontent.com/51216700/110002509-b36a5a00-7cd2-11eb-907a-ba736e3f679e.png)

Is `Lack of effort`
![image](https://user-images.githubusercontent.com/51216700/110002611-ced56500-7cd2-11eb-9458-e45528daab5e.png)

**Comment by raymondben** [comment]
Thanks, can you send me an example file pls? The `E` here should appear in the `skill_subtype` column as `Emergency` (with nothing in `special_code`). An `E` in the special code (third entry in the Extended set) corresponds to `Lack of effort`, so not quite sure what's gone awry.

**Comment by tyler-widdison** [comment]
[&2021hm-w-Clae_Spon-Klin-Ross.zip](https://github.com/openvolley/datavolley/files/6086496/2021hm-w-Clae_Spon-Klin-Ross.zip)

**Comment by raymondben** [comment]
I think the package behaviour is correct?
```
x$plays %>% dplyr::filter(skill ==  "Dig" & !is.na(skill_subtype)) %>% distinct(code, skill_subtype, special_code)
              code skill_subtype   special_code
1  a02DM+~~~41~E~E     Emergency Lack of effort
2  a02DT+~~~45BE~E     Emergency Lack of effort
3  *02DM+~~~47AE~E     Emergency Lack of effort
4  *01DH=~~~~~~E~E     Emergency Lack of effort
5  a02DH+~~~34DE~E     Emergency Lack of effort
6    *02DH=~~~36BE     Emergency           <NA>
7  *01DH-~~~~~~E~E     Emergency Lack of effort
8  a02DM=~~~49DE~E     Emergency Lack of effort
9  *02DH+~~~48DE~E     Emergency Lack of effort
10 *02DM+~~~29AE~E     Emergency Lack of effort
11 *02DH=~~~49DE~E     Emergency Lack of effort
12 a02DH=~~~29DE~E     Emergency Lack of effort
```

The `E` can mean two things, in character position 13 (skill_subtype) it means emergency, in position 15 (special_code) it's lack of effort. However, "lack of effort" (and the other special codes for digs, like "unplayable" and "referee call") ONLY apply to dig errors. Which is why your screenshot above doesn't show an entry spot for the other two extended code characters (number of players and special code). I am not sure why the scouted codes (pasted above) have the E in this position 15 slot on non-error digs - but given that they are there, `dv_read` is translating them correctly as far as I can tell?

**Comment by tyler-widdison** [comment]
🤦
