### ISSUE TITLE
Data read

### ISSUE THREAD

**Issue by ick003** [openvolley/datavolley#5]
- [ ] Ability to import from click&scout and augment data

**Comment by UndertheseaXD** [comment]
Hi I am having trouble using the dv_read functions, when I pass it a volleymetrics file I get this error
 Error in value[[3L]](cond) : 
  could not read the [3PLAYERS-H] section of the input file

**Comment by raymondben** [comment]
hi @UndertheseaXD , can you attach the file here please? That message indicates an issue with the file you are trying to read, but would need to see the actual file to say more.

**Comment by UndertheseaXD** [comment]
I figured out the problem, 

The issue is when there are duplicates in the section tags in the original data like this:

[3SET]
True; 8- 5;16- 7;21- 9;25-10;25;
True; 8- 6;16-10;21-13;25-14;25;
True; 8- 5;16-14;21-18;26-24;25;
True;;;;;25;
True;;;;;15;
[3PLAYERS-H]
[3PLAYERS-H]
0;0;1;;;;;;297497;Beach;Sandy;Beach;;;False;;;24265616368;253616E6479;24265616368;;;

**Comment by raymondben** [comment]
Yep, that would do it. That's not a valid file in that case. (For the record, I've never seen duplicated section headers like that before, that's a first!)
Will look at adding a more informative warning to the read function.
