### ISSUE TITLE
changes in `remap_player_names` are not reflected in `dv_write`

### ISSUE THREAD

**Issue by awosoga** [openvolley/datavolley#9]
First off, this package is incredible and I use it extensively. Thank you for your contribution to the open source volleyball analytics community.

I have been doing some player name validation and wanted to test out the `dv_write` function to save these changes. I know that the function is not completely ready yet, but it seemed to be good after changing the team names. However I noticed that after using `remap_player_names` that  those changes were not reflecting in the saved .dvw file. After browsing the source code I realized that this is because `remap_player_names` changes the `x$meta$players_h/v$name` column, but since `$name` is a derived column (not in the original .dvw file, but rather added in the `read_players` helper function in **meta.R**), it is dropped  when the `dvw_players_h/v` functions are called in **write.R** to write data to the new .dvw file. Therefore for changes to persist after `dv_write` is called, the changes in `remap_player_names` must actually go to `x$meta$players_h/v$firstname` and `x$meta$players_h/v$lastname` (and `x$meta$players_h/v$player_id`).

I made a modified function using `base::merge` which addresses these concerns and would be happy to submit a pull request should you wish to discuss this further. Thanks again for the great package!

**Comment by raymondben** [comment]
Thanks @awosoga for the kinds words but more for picking that up. You're right, the player name is made up from the first/last but changes are not reflected back to those columns. A PR would be very welcome! (If it were me, I think I'd try and automatically split each full name into its first/last, but also offer the possibility of providing the new first/last explicitly to `remap_player_names` , so that the user can enforce the correct names, if the auto-splitting gets it wrong. Presumably that's a risk with 3-word names, or anything else that doesn't follow a simple first/last pattern. But PR what you've got, and let's go from there ...)
Thanks!
